### ISSUE TITLE
Error in scan (file = file, ...  : line X did not have 6 elements 

### ISSUE THREAD

**Issue by scossin** [EHDEN/CatalogueExport#29] opened 2021-02-02 19:00 UTC
**Describe the bug**
https://github.com/EHDEN/CatalogueExport/blob/a7cdbd86e916e43ba1b67714236fc1eaf57b6320/R/CatalogueExport.R#L921
The error occurs if the log file doesn't contain 6 elements.

The log file doesn't contain 6 elements if only one of the queries doesn't work: an error is logged and the line added doesn't contain 6 elements: 
```R
ParallelLogger::logError(sprintf("Analysis %d -- ERROR %s", mainSql$analysisId, e))
```

This error is very annoying because it occurs at the end of all the SQL queries before the CATALOGUE_RESULTS tables are created so it seems difficult to recover from this error.    

**To Reproduce**
Run an analysis with the CatalogueExport::catalogueExport() containing a SQL error in one of the queries, with default parameters and numThreads=1

**Comment by PRijnbeek** [comment] 2021-02-02 19:29
Yes in principle no queries should fail and we may need to stop if they do to avoid these issues. Not sure about the 6 elements will try to reproduce (never happened earlier even when queries did fail for me).

**Comment by PRijnbeek** [comment] 2021-03-07 16:17
I am not able to reproduce this when I simulate an error in the query.

it then adds this row:

2021-03-07 17:07:20	[Main thread]	ERROR	CatalogueExport	3	Analysis 0 -- ERROR Error: Error executing SQL: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'synpuf.personP'. An error report has been created at  /Users/Rijnbeek/Documents/Github/EHDEN/CatalogueExport/errorReportSql.txt 

Which is read successfully:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/7252105/110246697-f180ab80-7f68-11eb-9459-4506ea67922d.png">

**Comment by PRijnbeek** [comment] 2021-03-07 16:47
Will close it when pulling in dev. Re-open if this still is an issue.

**Closed** 2021-03-07 18:30 UTC
Labels: bug
